//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shopping_Backup.WebServiceLextec {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceLextec.WebServiceLextecSoap")]
    public interface WebServiceLextecSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Desmatricular_Usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Desmatricular_Usuario(int sessionID, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllClases", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllClases();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTipos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllTipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIdAdministradorFromNombre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object GetIdAdministradorFromNombre(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIdClaseFromNombre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object GetIdClaseFromNombre(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIdTipoFromNombre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object GetIdTipoFromNombre(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Matricular_Usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Matricular_Usuario(int sessionID, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_ActualizarAdministrador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_ActualizarAdministrador(string name, string last_name1, string last_name2, string gender, string email, bool admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_ActualizarExperimento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_ActualizarExperimento(string name, string publicName, string note, string description, string place, bool isOpen, int classID, int typeID, string startDate, string endDate, bool isCompleted, int AdminID, int ID);
        
        // CODEGEN: Parameter 'file' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_ActualizarResultado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Online_Shopping_Backup.WebServiceLextec.SRSP_ActualizarResultadoResponse SRSP_ActualizarResultado(Online_Shopping_Backup.WebServiceLextec.SRSP_ActualizarResultadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_ActualizarSesion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_ActualizarSesion(int sessionID, System.DateTime date, System.DateTime startTime, System.DateTime endTime, bool full, int capacity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_ActualizarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_ActualizarUsuario(string name, string lastName1, string lastName2, string id, string email, string speciality, string nationality, string careerLevel, char gender, bool isStudent, string birthDate, string phone, string careerYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_EliminarAdministrador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_EliminarAdministrador(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_EliminarExperimento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_EliminarExperimento(int experimentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_EliminarResultado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_EliminarResultado(int resultID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_EliminarSesion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_EliminarSesion(int sesssionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_EliminarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_EliminarUsuario(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_FiltrarUsuariosLike", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SRSP_FiltrarUsuariosLike(string like, string speciality, string nationality, string careerLevel, string sex, string notExperiment, string student, string startDate, string endDate, string startQuatity, string endQuantity, string startRegisterDate, string endRegisterDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_InsertarAdministrador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_InsertarAdministrador(string name, string last_name1, string last_name2, string gender, string email, string password, string admin, string real_admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_InsertarClase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_InsertarClase(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_InsertarExperimento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_InsertarExperimento(string name, string publicName, string note, string description, string place, bool isOpen, int classID, int typeID, string startDate, string endDate, bool isCompleted, int AdminID);
        
        // CODEGEN: Parameter 'file' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_InsertarResultado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Online_Shopping_Backup.WebServiceLextec.SRSP_InsertarResultadoResponse SRSP_InsertarResultado(Online_Shopping_Backup.WebServiceLextec.SRSP_InsertarResultadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_InsertarSesion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_InsertarSesion(int experimentID, System.DateTime date, System.DateTime startTime, System.DateTime endTime, bool full, int capacity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_InsertarSesionxUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_InsertarSesionxUsuario(int userID, int sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_InsertarTipo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_InsertarTipo(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_InsertarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRSP_InsertarUsuario(string name, string lastName1, string lastName2, string id, string email, string speciality, string nationality, string careerLevel, char gender, bool isStudent, string birthDate, string phone, string careerYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_SeleccionarInvitacionesXCorreo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SRSP_SeleccionarInvitacionesXCorreo(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_SeleccionarInvitacionesXCorreoValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int[] SRSP_SeleccionarInvitacionesXCorreoValues(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_SelectInvitados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] SRSP_SelectInvitados(int experimentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_SesionExportarUsuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SRSP_SesionExportarUsuarios(int sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_VerResultado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SRSP_VerResultado(int resultID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_VerResultadoxSesion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SRSP_VerResultadoxSesion(int sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_VerificarAdministrador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SRSP_VerificarAdministrador();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_VerSesionesdeExperimento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SRSP_VerSesionesdeExperimento(int experimentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_VerUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SRSP_VerUsuario(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRSP_VisualizarExperimento5Param", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SRSP_VisualizarExperimento5Param(string idExperimiento, string idTipo, string idClase, string fechaInicio, string fechaFinal);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SRSP_ActualizarResultado", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SRSP_ActualizarResultadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int resultID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int size;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public SRSP_ActualizarResultadoRequest() {
        }
        
        public SRSP_ActualizarResultadoRequest(int resultID, int sessionID, string name, string type, int size, byte[] file) {
            this.resultID = resultID;
            this.sessionID = sessionID;
            this.name = name;
            this.type = type;
            this.size = size;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SRSP_ActualizarResultadoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SRSP_ActualizarResultadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable SRSP_ActualizarResultadoResult;
        
        public SRSP_ActualizarResultadoResponse() {
        }
        
        public SRSP_ActualizarResultadoResponse(System.Data.DataTable SRSP_ActualizarResultadoResult) {
            this.SRSP_ActualizarResultadoResult = SRSP_ActualizarResultadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SRSP_InsertarResultado", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SRSP_InsertarResultadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int size;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public SRSP_InsertarResultadoRequest() {
        }
        
        public SRSP_InsertarResultadoRequest(int sessionID, string name, string type, int size, byte[] file) {
            this.sessionID = sessionID;
            this.name = name;
            this.type = type;
            this.size = size;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SRSP_InsertarResultadoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SRSP_InsertarResultadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SRSP_InsertarResultadoResult;
        
        public SRSP_InsertarResultadoResponse() {
        }
        
        public SRSP_InsertarResultadoResponse(int SRSP_InsertarResultadoResult) {
            this.SRSP_InsertarResultadoResult = SRSP_InsertarResultadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceLextecSoapChannel : Online_Shopping_Backup.WebServiceLextec.WebServiceLextecSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceLextecSoapClient : System.ServiceModel.ClientBase<Online_Shopping_Backup.WebServiceLextec.WebServiceLextecSoap>, Online_Shopping_Backup.WebServiceLextec.WebServiceLextecSoap {
        
        public WebServiceLextecSoapClient() {
        }
        
        public WebServiceLextecSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceLextecSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLextecSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLextecSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Desmatricular_Usuario(int sessionID, string email) {
            base.Channel.Desmatricular_Usuario(sessionID, email);
        }
        
        public string[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Data.DataTable GetAllClases() {
            return base.Channel.GetAllClases();
        }
        
        public System.Data.DataTable GetAllTipos() {
            return base.Channel.GetAllTipos();
        }
        
        public object GetIdAdministradorFromNombre(string name) {
            return base.Channel.GetIdAdministradorFromNombre(name);
        }
        
        public object GetIdClaseFromNombre(string name) {
            return base.Channel.GetIdClaseFromNombre(name);
        }
        
        public object GetIdTipoFromNombre(string name) {
            return base.Channel.GetIdTipoFromNombre(name);
        }
        
        public void Matricular_Usuario(int sessionID, string email) {
            base.Channel.Matricular_Usuario(sessionID, email);
        }
        
        public int SRSP_ActualizarAdministrador(string name, string last_name1, string last_name2, string gender, string email, bool admin) {
            return base.Channel.SRSP_ActualizarAdministrador(name, last_name1, last_name2, gender, email, admin);
        }
        
        public int SRSP_ActualizarExperimento(string name, string publicName, string note, string description, string place, bool isOpen, int classID, int typeID, string startDate, string endDate, bool isCompleted, int AdminID, int ID) {
            return base.Channel.SRSP_ActualizarExperimento(name, publicName, note, description, place, isOpen, classID, typeID, startDate, endDate, isCompleted, AdminID, ID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Online_Shopping_Backup.WebServiceLextec.SRSP_ActualizarResultadoResponse Online_Shopping_Backup.WebServiceLextec.WebServiceLextecSoap.SRSP_ActualizarResultado(Online_Shopping_Backup.WebServiceLextec.SRSP_ActualizarResultadoRequest request) {
            return base.Channel.SRSP_ActualizarResultado(request);
        }
        
        public System.Data.DataTable SRSP_ActualizarResultado(int resultID, int sessionID, string name, string type, int size, byte[] file) {
            Online_Shopping_Backup.WebServiceLextec.SRSP_ActualizarResultadoRequest inValue = new Online_Shopping_Backup.WebServiceLextec.SRSP_ActualizarResultadoRequest();
            inValue.resultID = resultID;
            inValue.sessionID = sessionID;
            inValue.name = name;
            inValue.type = type;
            inValue.size = size;
            inValue.file = file;
            Online_Shopping_Backup.WebServiceLextec.SRSP_ActualizarResultadoResponse retVal = ((Online_Shopping_Backup.WebServiceLextec.WebServiceLextecSoap)(this)).SRSP_ActualizarResultado(inValue);
            return retVal.SRSP_ActualizarResultadoResult;
        }
        
        public int SRSP_ActualizarSesion(int sessionID, System.DateTime date, System.DateTime startTime, System.DateTime endTime, bool full, int capacity) {
            return base.Channel.SRSP_ActualizarSesion(sessionID, date, startTime, endTime, full, capacity);
        }
        
        public int SRSP_ActualizarUsuario(string name, string lastName1, string lastName2, string id, string email, string speciality, string nationality, string careerLevel, char gender, bool isStudent, string birthDate, string phone, string careerYear) {
            return base.Channel.SRSP_ActualizarUsuario(name, lastName1, lastName2, id, email, speciality, nationality, careerLevel, gender, isStudent, birthDate, phone, careerYear);
        }
        
        public int SRSP_EliminarAdministrador(string email) {
            return base.Channel.SRSP_EliminarAdministrador(email);
        }
        
        public int SRSP_EliminarExperimento(int experimentID) {
            return base.Channel.SRSP_EliminarExperimento(experimentID);
        }
        
        public int SRSP_EliminarResultado(int resultID) {
            return base.Channel.SRSP_EliminarResultado(resultID);
        }
        
        public int SRSP_EliminarSesion(int sesssionID) {
            return base.Channel.SRSP_EliminarSesion(sesssionID);
        }
        
        public int SRSP_EliminarUsuario(long id) {
            return base.Channel.SRSP_EliminarUsuario(id);
        }
        
        public System.Data.DataTable SRSP_FiltrarUsuariosLike(string like, string speciality, string nationality, string careerLevel, string sex, string notExperiment, string student, string startDate, string endDate, string startQuatity, string endQuantity, string startRegisterDate, string endRegisterDate) {
            return base.Channel.SRSP_FiltrarUsuariosLike(like, speciality, nationality, careerLevel, sex, notExperiment, student, startDate, endDate, startQuatity, endQuantity, startRegisterDate, endRegisterDate);
        }
        
        public int SRSP_InsertarAdministrador(string name, string last_name1, string last_name2, string gender, string email, string password, string admin, string real_admin) {
            return base.Channel.SRSP_InsertarAdministrador(name, last_name1, last_name2, gender, email, password, admin, real_admin);
        }
        
        public int SRSP_InsertarClase(string name) {
            return base.Channel.SRSP_InsertarClase(name);
        }
        
        public int SRSP_InsertarExperimento(string name, string publicName, string note, string description, string place, bool isOpen, int classID, int typeID, string startDate, string endDate, bool isCompleted, int AdminID) {
            return base.Channel.SRSP_InsertarExperimento(name, publicName, note, description, place, isOpen, classID, typeID, startDate, endDate, isCompleted, AdminID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Online_Shopping_Backup.WebServiceLextec.SRSP_InsertarResultadoResponse Online_Shopping_Backup.WebServiceLextec.WebServiceLextecSoap.SRSP_InsertarResultado(Online_Shopping_Backup.WebServiceLextec.SRSP_InsertarResultadoRequest request) {
            return base.Channel.SRSP_InsertarResultado(request);
        }
        
        public int SRSP_InsertarResultado(int sessionID, string name, string type, int size, byte[] file) {
            Online_Shopping_Backup.WebServiceLextec.SRSP_InsertarResultadoRequest inValue = new Online_Shopping_Backup.WebServiceLextec.SRSP_InsertarResultadoRequest();
            inValue.sessionID = sessionID;
            inValue.name = name;
            inValue.type = type;
            inValue.size = size;
            inValue.file = file;
            Online_Shopping_Backup.WebServiceLextec.SRSP_InsertarResultadoResponse retVal = ((Online_Shopping_Backup.WebServiceLextec.WebServiceLextecSoap)(this)).SRSP_InsertarResultado(inValue);
            return retVal.SRSP_InsertarResultadoResult;
        }
        
        public int SRSP_InsertarSesion(int experimentID, System.DateTime date, System.DateTime startTime, System.DateTime endTime, bool full, int capacity) {
            return base.Channel.SRSP_InsertarSesion(experimentID, date, startTime, endTime, full, capacity);
        }
        
        public int SRSP_InsertarSesionxUsuario(int userID, int sessionID) {
            return base.Channel.SRSP_InsertarSesionxUsuario(userID, sessionID);
        }
        
        public int SRSP_InsertarTipo(string nombre) {
            return base.Channel.SRSP_InsertarTipo(nombre);
        }
        
        public int SRSP_InsertarUsuario(string name, string lastName1, string lastName2, string id, string email, string speciality, string nationality, string careerLevel, char gender, bool isStudent, string birthDate, string phone, string careerYear) {
            return base.Channel.SRSP_InsertarUsuario(name, lastName1, lastName2, id, email, speciality, nationality, careerLevel, gender, isStudent, birthDate, phone, careerYear);
        }
        
        public System.Data.DataTable SRSP_SeleccionarInvitacionesXCorreo(string email) {
            return base.Channel.SRSP_SeleccionarInvitacionesXCorreo(email);
        }
        
        public int[] SRSP_SeleccionarInvitacionesXCorreoValues(string email) {
            return base.Channel.SRSP_SeleccionarInvitacionesXCorreoValues(email);
        }
        
        public string[] SRSP_SelectInvitados(int experimentID) {
            return base.Channel.SRSP_SelectInvitados(experimentID);
        }
        
        public System.Data.DataTable SRSP_SesionExportarUsuarios(int sessionID) {
            return base.Channel.SRSP_SesionExportarUsuarios(sessionID);
        }
        
        public System.Data.DataTable SRSP_VerResultado(int resultID) {
            return base.Channel.SRSP_VerResultado(resultID);
        }
        
        public System.Data.DataTable SRSP_VerResultadoxSesion(int sessionID) {
            return base.Channel.SRSP_VerResultadoxSesion(sessionID);
        }
        
        public System.Data.DataTable SRSP_VerificarAdministrador() {
            return base.Channel.SRSP_VerificarAdministrador();
        }
        
        public System.Data.DataTable SRSP_VerSesionesdeExperimento(int experimentID) {
            return base.Channel.SRSP_VerSesionesdeExperimento(experimentID);
        }
        
        public System.Data.DataTable SRSP_VerUsuario(string email) {
            return base.Channel.SRSP_VerUsuario(email);
        }
        
        public System.Data.DataTable SRSP_VisualizarExperimento5Param(string idExperimiento, string idTipo, string idClase, string fechaInicio, string fechaFinal) {
            return base.Channel.SRSP_VisualizarExperimento5Param(idExperimiento, idTipo, idClase, fechaInicio, fechaFinal);
        }
    }
}
